<a href="https://colab.research.google.com/github/mfernandezzz/mediciones_sensores/blob/main/mediciones_sensores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Realizar una limpieza de datos lo mas acertada posible de una hoja de calculo que contiene registros correspondientes a mediciones de sensores.**

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel('/content/mediciones_sensores.xlsx')
df

,id_medición,fecha_hora,id_sensor,temperatura,humedad,presión,vel_viento,rayos_uv
0,81a078fe,2023-02-28 04:50:00,sen3,32.5°C,NaN,1022.4,viento moderado,ALTO
1,43cfa7ba,2023-01-11 03:12:00,SEN5,34.3,68.9,1017.4,3.0,Alto
2,8e576280,2023-01-03 06:38:00,SEN2,33.6,42.0,1004.4,2025-08-13 00:00:00,ALTO
3,611a37c3,2023-03-09 11:56:00,SEN3,2025-01-30 00:00:00,44.1,1013.4,2025-09-17 00:00:00,Alto
4,50ff25ae,2023-01-26 00:48:00,SEN1,2025-08-28 00:00:00,72.9,1015.7,2025-02-17 00:00:00,Bajo
...,...,...,...,...,...,...,...,...
100,893930,2023-02-02 08:06:00,SEN1,2025-07-29 00:00:00,57.9,1011.7,2025-08-16 00:00:00,ALTO
101,f63d551d,2023-01-04 22:55:00,SEN3,2025-05-16 00:00:00,52.6,1013.2,2025-03-09 00:00:00,ALTO
102,49aa188d,2023-03-02 04:33:00,sen3,2025-08-22 00:00:00,74.6,997.4,2025-08-10 00:00:00,moderado
103,b27c833b,2023-01-10 07:16:00,SEN4,32.5°C,NaN,1014.0,2025-06-01 00:00:00,Bajo
104,895b9285,2023-01-31 15:18:00,SEN5,31.0,77.1,1018.2,2025-09-17 00:00:00,Moderado

Transformar la hoja de calculo a un archivo csv

In [3]:
df.to_csv('mediciones_sensores.csv') #index=False, encoding='utf-8'

In [4]:
df.head()

,id_medición,fecha_hora,id_sensor,temperatura,humedad,presión,vel_viento,rayos_uv
0,81a078fe,2023-02-28 04:50:00,sen3,32.5°C,NaN,1022.4,viento moderado,ALTO
1,43cfa7ba,2023-01-11 03:12:00,SEN5,34.3,68.9,1017.4,3.0,Alto
2,8e576280,2023-01-03 06:38:00,SEN2,33.6,42.0,1004.4,2025-08-13 00:00:00,ALTO
3,611a37c3,2023-03-09 11:56:00,SEN3,2025-01-30 00:00:00,44.1,1013.4,2025-09-17 00:00:00,Alto
4,50ff25ae,2023-01-26 00:48:00,SEN1,2025-08-28 00:00:00,72.9,1015.7,2025-02-17 00:00:00,Bajo

**Obtener informacion de los datos almacenados en el dataframe**

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105 entries, 0 to 104
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id_medición  105 non-null    object
 1   fecha_hora   105 non-null    datetime64[ns]
 2   id_sensor    105 non-null    object
 3   temperatura  105 non-null    object
 4   humedad      92 non-null     float64
 5   presión      105 non-null    float64
 6   vel_viento   105 non-null    object
 7   rayos_uv     105 non-null    object
dtypes: datetime64[ns](1), float64(2), object(5)
memory usage: 6.7+ KB

**Obtener estadisticas basicas de los datos numericos almacenados en el dataframe**

In [6]:
df.describe()

                          fecha_hora    humedad      presión
count                            105  92.000000   105.000000
mean   2023-02-03 12:06:29.714285824  63.785870  1008.848571
min              2023-01-01 14:11:00  40.500000   991.000000
25%              2023-01-15 20:57:00  52.100000  1001.300000
50%              2023-02-02 08:06:00  62.500000  1010.300000
75%              2023-02-23 17:57:00  74.600000  1016.900000
max              2023-03-11 01:38:00  89.200000  1024.400000
std                              NaN  14.717737     9.585948

**Visualizar el tipo de dato que almacena cada columna**

In [7]:
df.dtypes

id_medición            object
fecha_hora     datetime64[ns]
id_sensor              object
temperatura            object
humedad               float64
presión               float64
vel_viento             object
rayos_uv               object
dtype: object

**Comprobar si un id se repite mas de una vez (existencia de filas duplicadas)**

In [8]:
df['id_medición'].value_counts()

id_medición
49aa188d    2
f63d551d    2
895b9285    2
b27c833b    2
893930      2
           ..
3bb53859    1
fed7c593    1
bbd0c5b3    1
f0f22f0a    1
1f1d6bd1    1
Name: count, Length: 100, dtype: int64

**Establecer la columna id_medicion como el indice del dataframe**

In [9]:
df.set_index('id_medición', inplace=True)
df

,fecha_hora,id_sensor,temperatura,humedad,presión,vel_viento,rayos_uv
id_medición,,,,,,,
81a078fe,2023-02-28 04:50:00,sen3,32.5°C,NaN,1022.4,viento moderado,ALTO
43cfa7ba,2023-01-11 03:12:00,SEN5,34.3,68.9,1017.4,3.0,Alto
8e576280,2023-01-03 06:38:00,SEN2,33.6,42.0,1004.4,2025-08-13 00:00:00,ALTO
611a37c3,2023-03-09 11:56:00,SEN3,2025-01-30 00:00:00,44.1,1013.4,2025-09-17 00:00:00,Alto
50ff25ae,2023-01-26 00:48:00,SEN1,2025-08-28 00:00:00,72.9,1015.7,2025-02-17 00:00:00,Bajo
...,...,...,...,...,...,...,...
893930,2023-02-02 08:06:00,SEN1,2025-07-29 00:00:00,57.9,1011.7,2025-08-16 00:00:00,ALTO
f63d551d,2023-01-04 22:55:00,SEN3,2025-05-16 00:00:00,52.6,1013.2,2025-03-09 00:00:00,ALTO
49aa188d,2023-03-02 04:33:00,sen3,2025-08-22 00:00:00,74.6,997.4,2025-08-10 00:00:00,moderado
b27c833b,2023-01-10 07:16:00,SEN4,32.5°C,NaN,1014.0,2025-06-01 00:00:00,Bajo
895b9285,2023-01-31 15:18:00,SEN5,31.0,77.1,1018.2,2025-09-17 00:00:00,Moderado

**Comprobar la cantidad de sensores**

In [10]:
df['id_sensor'].value_counts()

id_sensor
SEN5    23
SEN2    19
SEN1    18
SEN4    18
SEN3    16
sen3     5
sen1     2
sen2     2
sen5     2
Name: count, dtype: int64

**Pasar los id de sensores en minuscula a mayuscula**

In [11]:
df['id_sensor'] = df['id_sensor'].str.upper()
df['id_sensor'].value_counts()

id_sensor
SEN5    25
SEN3    21
SEN2    21
SEN1    20
SEN4    18
Name: count, dtype: int64

**Buscar errores de tipeo en la columna rayos uv**

In [12]:
df['rayos_uv'].value_counts()

rayos_uv
ALTO        23
Alto        23
Bajo        21
moderado    20
Moderado    18
Name: count, dtype: int64

**Corregir los errores de tipeo en la columna rayos_uv**

In [13]:
df['rayos_uv'] = df['rayos_uv'].str.upper()
df['rayos_uv'].value_counts()

rayos_uv
ALTO        46
MODERADO    38
BAJO        21
Name: count, dtype: int64

In [14]:
#visualizar la cantidad de filas que tiene el dataframe
df.shape[0]

105

**Eliminar filas duplicadas y ordenar las mismas en base a la columna fecha y hora**

In [15]:
df = df.drop_duplicates().sort_values('fecha_hora')
df.shape[0]

100

**Cambiar el nombre de la columna temperatura**

In [16]:
#almacenar los nombres de las columnas en una lista
cols = df.columns.tolist()
#ubicar el nombre de columna a modificar y asignar el nuevo nombre
cols[cols.index('temperatura')] = 'temperatura (°C)'
#se realizan las modificaciones de cambio de nombre a las columnas del dataframe
df.columns = cols
df.head(10)

,fecha_hora,id_sensor,temperatura (°C),humedad,presión,vel_viento,rayos_uv
id_medición,,,,,,,
1473229f,2023-01-01 14:11:00,SEN1,2025-02-28 00:00:00,66.4,1017.5,2025-05-05 00:00:00,MODERADO
8e576280,2023-01-03 06:38:00,SEN2,33.6,42.0,1004.4,2025-08-13 00:00:00,ALTO
99c4533b,2023-01-03 09:58:00,SEN5,2025-03-25 00:00:00,65.3,1007.8,2025-03-16 00:00:00,MODERADO
1580151b,2023-01-03 17:05:00,SEN4,2025-01-15 00:00:00,40.5,1013.1,2025-03-09 00:00:00,MODERADO
fb444e43,2023-01-03 21:25:00,SEN4,2025-08-26 00:00:00,86.8,997.8,viento moderado,BAJO
f63d551d,2023-01-04 22:55:00,SEN3,2025-05-16 00:00:00,52.6,1013.2,2025-03-09 00:00:00,ALTO
f8f58403,2023-01-05 04:06:00,SEN2,15.0,87.3,1000.6,2025-07-16 00:00:00,ALTO
e6bf6b53,2023-01-07 07:56:00,SEN2,2025-03-18 00:00:00,45.6,1019.2,2025-08-17 00:00:00,MODERADO
c1ed9550,2023-01-07 11:58:00,SEN5,32.5°C,NaN,991.6,2025-03-13 00:00:00,ALTO
8d573a04,2023-01-08 04:08:00,SEN1,2025-03-15 00:00:00,42.2,1014.4,2025-09-18 00:00:00,ALTO

**Verificar si la columna presion contiene valores nulos (nan)**

In [17]:
presion_null = np.isnan(df['presión'])
presion_null.value_counts()

presión
False    100
Name: count, dtype: int64

**Verificar si la columna humedad contiene valores nulos**

In [18]:
humedad_null = np.isnan(df['humedad'])
humedad_null.value_counts()

humedad
False    88
True     12
Name: count, dtype: int64

Dada la existencia de valores nulos dentro de la columna 'humedad', se procede a obtener el valor medio de los valores validos ingresados dentro de la columna y sustituir los valores nan por el valor medio obtenido.

In [19]:
#obtener un numpy array con todos los valores dentro de la columna humedad
humedad_values = np.array(df['humedad'])
#obtener el valor medio de humedad excluyendo los valores nan
mean_humedad = humedad_values[~np.isnan(humedad_values)].mean()
round(mean_humedad, 1)

np.float64(63.7)

In [20]:
#sustituir los valores nan por el valor medio de humedad obtenido previamente
df['humedad'] = df['humedad'].fillna(round(mean_humedad, 1))
df.head(10)

,fecha_hora,id_sensor,temperatura (°C),humedad,presión,vel_viento,rayos_uv
id_medición,,,,,,,
1473229f,2023-01-01 14:11:00,SEN1,2025-02-28 00:00:00,66.4,1017.5,2025-05-05 00:00:00,MODERADO
8e576280,2023-01-03 06:38:00,SEN2,33.6,42.0,1004.4,2025-08-13 00:00:00,ALTO
99c4533b,2023-01-03 09:58:00,SEN5,2025-03-25 00:00:00,65.3,1007.8,2025-03-16 00:00:00,MODERADO
1580151b,2023-01-03 17:05:00,SEN4,2025-01-15 00:00:00,40.5,1013.1,2025-03-09 00:00:00,MODERADO
fb444e43,2023-01-03 21:25:00,SEN4,2025-08-26 00:00:00,86.8,997.8,viento moderado,BAJO
f63d551d,2023-01-04 22:55:00,SEN3,2025-05-16 00:00:00,52.6,1013.2,2025-03-09 00:00:00,ALTO
f8f58403,2023-01-05 04:06:00,SEN2,15.0,87.3,1000.6,2025-07-16 00:00:00,ALTO
e6bf6b53,2023-01-07 07:56:00,SEN2,2025-03-18 00:00:00,45.6,1019.2,2025-08-17 00:00:00,MODERADO
c1ed9550,2023-01-07 11:58:00,SEN5,32.5°C,63.7,991.6,2025-03-13 00:00:00,ALTO
8d573a04,2023-01-08 04:08:00,SEN1,2025-03-15 00:00:00,42.2,1014.4,2025-09-18 00:00:00,ALTO

In [21]:
#verificar si la columna humedad sigue teniendo valores nan
humedad_null = np.isnan(df['humedad'])
humedad_null.value_counts()

humedad
False    100
Name: count, dtype: int64

In [22]:
df['temperatura (°C)'].value_counts()

temperatura (°C)
32.5°C                 7
2025-02-16 00:00:00    4
2025-01-23 00:00:00    3
2025-03-16 00:00:00    2
2025-07-30 00:00:00    2
                      ..
32.6                   1
31.2                   1
2025-05-22 00:00:00    1
20.0                   1
2025-01-22 00:00:00    1
Name: count, Length: 75, dtype: int64

La columna temperatura contiene datos confusos. Se puede encontrar datos de fecha, numericos y numericos seguido de ºC siempre como cadena de caracteres. Por consiguiente, se eliminara de los registros el caracter ºC de aquellos string que lo contengan. A su vez, los registros correspondientes a fecha se sustituyen por registros nan.

In [23]:
df['temperatura (°C)'] = df['temperatura (°C)'].str.replace('°C', '')
df.head(10)

,fecha_hora,id_sensor,temperatura (°C),humedad,presión,vel_viento,rayos_uv
id_medición,,,,,,,
1473229f,2023-01-01 14:11:00,SEN1,NaN,66.4,1017.5,2025-05-05 00:00:00,MODERADO
8e576280,2023-01-03 06:38:00,SEN2,33.6,42.0,1004.4,2025-08-13 00:00:00,ALTO
99c4533b,2023-01-03 09:58:00,SEN5,NaN,65.3,1007.8,2025-03-16 00:00:00,MODERADO
1580151b,2023-01-03 17:05:00,SEN4,NaN,40.5,1013.1,2025-03-09 00:00:00,MODERADO
fb444e43,2023-01-03 21:25:00,SEN4,NaN,86.8,997.8,viento moderado,BAJO
f63d551d,2023-01-04 22:55:00,SEN3,NaN,52.6,1013.2,2025-03-09 00:00:00,ALTO
f8f58403,2023-01-05 04:06:00,SEN2,15.0,87.3,1000.6,2025-07-16 00:00:00,ALTO
e6bf6b53,2023-01-07 07:56:00,SEN2,NaN,45.6,1019.2,2025-08-17 00:00:00,MODERADO
c1ed9550,2023-01-07 11:58:00,SEN5,32.5,63.7,991.6,2025-03-13 00:00:00,ALTO
8d573a04,2023-01-08 04:08:00,SEN1,NaN,42.2,1014.4,2025-09-18 00:00:00,ALTO

Los valores nan seran sustituidos por el valor medio de las temperaturas registradas correctamente.

In [24]:
df['temperatura (°C)'].value_counts()

temperatura (°C)
32.5    8
33.0    2
32.3    2
15.0    1
29.2    1
33.6    1
34.3    1
28.0    1
32.0    1
23.0    1
33.5    1
32.2    1
16.0    1
31.0    1
32.1    1
33.8    1
17.0    1
24.0    1
33.4    1
32.6    1
31.2    1
20.0    1
Name: count, dtype: int64

In [25]:
#cambiar los valores de la columna temperatura a type float
df['temperatura (°C)'] = df['temperatura (°C)'].astype(float)
df.dtypes

fecha_hora          datetime64[ns]
id_sensor                   object
temperatura (°C)           float64
humedad                    float64
presión                    float64
vel_viento                  object
rayos_uv                    object
dtype: object

In [26]:
#obtener los valores de temperatura en un numpy array
values_temperatura = np.array(df['temperatura (°C)'])
#obtener el valor medio de temperatura excluyendo los valores nan
mean_temperatura = values_temperatura[~np.isnan(values_temperatura)].mean()
round(mean_temperatura, 1)

np.float64(29.8)

In [27]:
#sustituir los valores nan por los valores medios de temperatura
df['temperatura (°C)'] = df['temperatura (°C)'].fillna(round(mean_temperatura, 1))
df.head(10)

,fecha_hora,id_sensor,temperatura (°C),humedad,presión,vel_viento,rayos_uv
id_medición,,,,,,,
1473229f,2023-01-01 14:11:00,SEN1,29.8,66.4,1017.5,2025-05-05 00:00:00,MODERADO
8e576280,2023-01-03 06:38:00,SEN2,33.6,42.0,1004.4,2025-08-13 00:00:00,ALTO
99c4533b,2023-01-03 09:58:00,SEN5,29.8,65.3,1007.8,2025-03-16 00:00:00,MODERADO
1580151b,2023-01-03 17:05:00,SEN4,29.8,40.5,1013.1,2025-03-09 00:00:00,MODERADO
fb444e43,2023-01-03 21:25:00,SEN4,29.8,86.8,997.8,viento moderado,BAJO
f63d551d,2023-01-04 22:55:00,SEN3,29.8,52.6,1013.2,2025-03-09 00:00:00,ALTO
f8f58403,2023-01-05 04:06:00,SEN2,15.0,87.3,1000.6,2025-07-16 00:00:00,ALTO
e6bf6b53,2023-01-07 07:56:00,SEN2,29.8,45.6,1019.2,2025-08-17 00:00:00,MODERADO
c1ed9550,2023-01-07 11:58:00,SEN5,32.5,63.7,991.6,2025-03-13 00:00:00,ALTO
8d573a04,2023-01-08 04:08:00,SEN1,29.8,42.2,1014.4,2025-09-18 00:00:00,ALTO

In [28]:
#obtener la cantidad de veces que se obtuvieron los valores respectivos a la columna rayos uv
df['rayos_uv'].value_counts()

rayos_uv
ALTO        44
MODERADO    36
BAJO        20
Name: count, dtype: int64

Si se realiza un vistazo rapido a algunos de los datos del dataframe, se puede apreciar que determinada informacion almacenada en las columnas no coincide con la informacion almacenada en otra columna. Por ejemplo, la medicion con id f8f58403 tiene un valor de rayos uv ALTO, lo cual es irracional teniendo en cuenta que la medicion fue realizada a las 04:06. Por consiguiente, se debe llevar adelante una normalizacion de los datos. Para la misma, teniendo en cuenta que las mediciones fueron realizadas durante el verano, se determinara que durante el horario de la noche (a partir de las 21:00) y hasta la salida del sol (aproximadamente las 06:00) el indice de rayos uv sera NULO.

In [29]:
#asignar el valor NULO en la columna rayos uv si en la columna fecha_hora la hora se encuentra en el rango de las 21:00 y 06:00

#especificando valor de hora pero no minutos
#hour = df['fecha_hora'].dt.hour
#cond_noche = (hour >= 21) | (hour <= 6)
#df.loc[cond_noche, 'rayos_uv'] = 'BAJO'

#especificando un rango horario con horas exactas
#se extrae y almacena los valores de hora correspondientes a la columna fecha_hora
time = df['fecha_hora'].dt.time

#se importa la libreria correspondiente
from datetime import time as dtime
#valores de hora que determinan el rango horario y su condicion correspondiente
start, end = dtime(21, 0, 0), dtime(6, 0, 0)
cond_noche = df['fecha_hora'].dt.time >= start
cond_early = df['fecha_hora'].dt.time <= end
#variable que almacena el rango horario
horario_nocturno = cond_noche | cond_early
#se localiza los registros dentro del rango horario y se asigna el nuevo valor en la columna rayos_uv
df.loc[horario_nocturno, 'rayos_uv'] = 'NULO'
df.head(15)

,fecha_hora,id_sensor,temperatura (°C),humedad,presión,vel_viento,rayos_uv
id_medición,,,,,,,
1473229f,2023-01-01 14:11:00,SEN1,29.8,66.4,1017.5,2025-05-05 00:00:00,MODERADO
8e576280,2023-01-03 06:38:00,SEN2,33.6,42.0,1004.4,2025-08-13 00:00:00,ALTO
99c4533b,2023-01-03 09:58:00,SEN5,29.8,65.3,1007.8,2025-03-16 00:00:00,MODERADO
1580151b,2023-01-03 17:05:00,SEN4,29.8,40.5,1013.1,2025-03-09 00:00:00,MODERADO
fb444e43,2023-01-03 21:25:00,SEN4,29.8,86.8,997.8,viento moderado,NULO
f63d551d,2023-01-04 22:55:00,SEN3,29.8,52.6,1013.2,2025-03-09 00:00:00,NULO
f8f58403,2023-01-05 04:06:00,SEN2,15.0,87.3,1000.6,2025-07-16 00:00:00,NULO
e6bf6b53,2023-01-07 07:56:00,SEN2,29.8,45.6,1019.2,2025-08-17 00:00:00,MODERADO
c1ed9550,2023-01-07 11:58:00,SEN5,32.5,63.7,991.6,2025-03-13 00:00:00,ALTO
8d573a04,2023-01-08 04:08:00,SEN1,29.8,42.2,1014.4,2025-09-18 00:00:00,NULO
412652be,2023-01-08 06:18:00,SEN5,29.8,41.8,1001.3,16.0,ALTO
9af46357,2023-01-08 21:55:00,SEN3,29.8,72.3,1002.2,2025-03-18 00:00:00,NULO
d3057fef,2023-01-09 10:36:00,SEN5,29.8,47.8,1022.9,3.0,ALTO
6d71f038,2023-01-09 12:40:00,SEN2,29.2,63.7,1003.9,2025-06-10 00:00:00,MODERADO
363aee17,2023-01-09 19:16:00,SEN5,29.8,50.5,996.9,viento moderado,BAJO

In [30]:
#obtener la cantidad de veces que se registro cada nivel de rayos_uv
df['rayos_uv'].value_counts()

rayos_uv
NULO        38
ALTO        26
MODERADO    24
BAJO        12
Name: count, dtype: int64

Si se realiza un nuevo vistazo rapido a los datos, se puede observar que siguen existiendo registros incongruentes entre columnas. Por ejemplo, en la medicion con id 8e576280 se registro un indice de rayos uv ALTO, lo cual es irracional teniendo en cuenta que el sensor realizo ese registro a las 06:18 de la mañana. Por consiguiente, no es logico que poco despues del amanecer se registre nivel de rayos uv ALTO. Para esta normalizacion de los datos, se establecera un nivel de radiacion uv BAJO en todas aquellas mediciones relizadas en el horario de 06:01 a 08:00.

In [31]:
#especificar los horarios que determinan el rango horario y su condicion correspondiente
start, end = dtime(6, 1, 0), dtime(8, 0, 0)
cond_first_hour = df['fecha_hora'].dt.time >= start
cond_early_morning = df['fecha_hora'].dt.time <= end
#variable que almacena el rango horario
horario_mañana = cond_first_hour & cond_early_morning
#localizar los registros dentro del rango horario y asignar el nuevo valor en la columna rayos_uv
df.loc[horario_mañana, 'rayos_uv'] = 'BAJO'
df.head(15)

,fecha_hora,id_sensor,temperatura (°C),humedad,presión,vel_viento,rayos_uv
id_medición,,,,,,,
1473229f,2023-01-01 14:11:00,SEN1,29.8,66.4,1017.5,2025-05-05 00:00:00,MODERADO
8e576280,2023-01-03 06:38:00,SEN2,33.6,42.0,1004.4,2025-08-13 00:00:00,BAJO
99c4533b,2023-01-03 09:58:00,SEN5,29.8,65.3,1007.8,2025-03-16 00:00:00,MODERADO
1580151b,2023-01-03 17:05:00,SEN4,29.8,40.5,1013.1,2025-03-09 00:00:00,MODERADO
fb444e43,2023-01-03 21:25:00,SEN4,29.8,86.8,997.8,viento moderado,NULO
f63d551d,2023-01-04 22:55:00,SEN3,29.8,52.6,1013.2,2025-03-09 00:00:00,NULO
f8f58403,2023-01-05 04:06:00,SEN2,15.0,87.3,1000.6,2025-07-16 00:00:00,NULO
e6bf6b53,2023-01-07 07:56:00,SEN2,29.8,45.6,1019.2,2025-08-17 00:00:00,BAJO
c1ed9550,2023-01-07 11:58:00,SEN5,32.5,63.7,991.6,2025-03-13 00:00:00,ALTO
8d573a04,2023-01-08 04:08:00,SEN1,29.8,42.2,1014.4,2025-09-18 00:00:00,NULO
412652be,2023-01-08 06:18:00,SEN5,29.8,41.8,1001.3,16.0,BAJO
9af46357,2023-01-08 21:55:00,SEN3,29.8,72.3,1002.2,2025-03-18 00:00:00,NULO
d3057fef,2023-01-09 10:36:00,SEN5,29.8,47.8,1022.9,3.0,ALTO
6d71f038,2023-01-09 12:40:00,SEN2,29.2,63.7,1003.9,2025-06-10 00:00:00,MODERADO
363aee17,2023-01-09 19:16:00,SEN5,29.8,50.5,996.9,viento moderado,BAJO

In [32]:
df.tail(15)

,fecha_hora,id_sensor,temperatura (°C),humedad,presión,vel_viento,rayos_uv
id_medición,,,,,,,
49aa188d,2023-03-02 04:33:00,SEN3,29.8,74.6,997.4,2025-08-10 00:00:00,NULO
cb657fa8,2023-03-03 00:01:00,SEN5,29.8,73.3,1023.3,2025-06-19 00:00:00,NULO
e6b6a036,2023-03-03 14:16:00,SEN1,24.0,55.7,1006.5,2025-09-13 00:00:00,MODERADO
1cf486b1,2023-03-04 05:13:00,SEN4,33.4,83.7,1018.2,viento moderado,NULO
1ce573f1,2023-03-05 13:06:00,SEN2,32.3,67.7,994.0,2025-08-04 00:00:00,MODERADO
920aabaf,2023-03-05 20:04:00,SEN4,32.6,52.2,1020.7,2025-09-08 00:00:00,MODERADO
241b495b,2023-03-05 21:08:00,SEN1,29.8,68.0,1000.9,2025-01-18 00:00:00,NULO
b28f200d,2023-03-06 03:09:00,SEN5,33.0,68.0,1004.2,2025-08-07 00:00:00,NULO
23f3ebb8,2023-03-07 04:10:00,SEN4,29.8,43.4,1001.6,2025-05-08 00:00:00,NULO
3bb53859,2023-03-08 08:48:00,SEN2,29.8,80.0,1021.0,2025-02-05 00:00:00,ALTO
cee8b1a6,2023-03-08 10:07:00,SEN1,31.2,63.7,994.4,2025-02-01 00:00:00,ALTO
77122c46,2023-03-09 00:50:00,SEN4,29.8,73.5,1003.4,viento moderado,NULO
0eace0dd,2023-03-09 10:00:00,SEN2,20.0,53.3,997.0,2025-03-09 00:00:00,BAJO
611a37c3,2023-03-09 11:56:00,SEN3,29.8,44.1,1013.4,2025-09-17 00:00:00,ALTO
a1073a10,2023-03-11 01:38:00,SEN1,29.8,63.7,1005.3,2025-06-15 00:00:00,NULO

In [33]:
df['rayos_uv'].value_counts()

rayos_uv
NULO        38
BAJO        23
MODERADO    21
ALTO        18
Name: count, dtype: int64

Dado que las mediciones fueron realizadas durante el verano, se puede determinar que el horario de mayor radiacion uv es entre las 11:00 y las 18:00 aproximadamente. Por consiguiente, fuera de ese horario y antes de las 21:00 el nivel de rayos uv debe ser MODERADO o BAJO. Consultar la cantidad de veces que se registro cada nivel de rayos uv en el rango horario de 18:00 a 21:00.

In [34]:
#extraer todas las mediciones realizadas durante el horario de las 18:00 y las 21:00
start, end = dtime(18, 0, 0), dtime(21, 0, 0)
mask = df['fecha_hora'].dt.time.between(start, end)
atardecer = df[mask]
atardecer

,fecha_hora,id_sensor,temperatura (°C),humedad,presión,vel_viento,rayos_uv
id_medición,,,,,,,
363aee17,2023-01-09 19:16:00,SEN5,29.8,50.5,996.9,viento moderado,BAJO
73b4b14b,2023-01-15 19:19:00,SEN3,29.8,63.7,999.9,16.0,ALTO
bbd0c5b3,2023-01-15 20:57:00,SEN5,29.8,60.6,1015.1,2025-05-06 00:00:00,ALTO
985ab1b7,2023-02-11 19:37:00,SEN3,32.1,85.4,1021.5,2025-07-16 00:00:00,BAJO
a2fa0c39,2023-02-18 19:24:00,SEN4,17.0,42.5,1007.7,viento moderado,MODERADO
864d8ba3,2023-02-24 19:07:00,SEN5,29.8,66.9,1002.3,2025-09-08 00:00:00,BAJO
691a8c22,2023-02-27 19:07:00,SEN2,29.8,86.3,1011.4,2025-06-08 00:00:00,ALTO
1c555871,2023-02-27 20:40:00,SEN1,29.8,86.7,1015.8,2025-04-13 00:00:00,BAJO
920aabaf,2023-03-05 20:04:00,SEN4,32.6,52.2,1020.7,2025-09-08 00:00:00,MODERADO

De las mediciones realizadas en el rango horario especificado, tres de las mismas tienen asociado un nivel de rayos uv ALTO. Modificar esos tres registros y asignar nivel de rayos uv MODERADO.

In [35]:
start, end = dtime(18, 0, 0), dtime(21, 0, 0)
value_rayos_uv = 'ALTO'
value_to_assign = 'MODERADO'
mask_time = df['fecha_hora'].dt.time.between(start, end)
mask_rayos_uv = df['rayos_uv'] == value_rayos_uv
df.loc[mask_time & mask_rayos_uv, 'rayos_uv'] = value_to_assign

In [36]:
#se vuelve a mostrar las mediciones realizadas durante el horario de 18:00 a 21:00 para comprobar cambios
start, end = dtime(18, 0, 0), dtime(21, 0, 0)
mask = df['fecha_hora'].dt.time.between(start, end)
atardecer = df[mask]
atardecer

,fecha_hora,id_sensor,temperatura (°C),humedad,presión,vel_viento,rayos_uv
id_medición,,,,,,,
363aee17,2023-01-09 19:16:00,SEN5,29.8,50.5,996.9,viento moderado,BAJO
73b4b14b,2023-01-15 19:19:00,SEN3,29.8,63.7,999.9,16.0,MODERADO
bbd0c5b3,2023-01-15 20:57:00,SEN5,29.8,60.6,1015.1,2025-05-06 00:00:00,MODERADO
985ab1b7,2023-02-11 19:37:00,SEN3,32.1,85.4,1021.5,2025-07-16 00:00:00,BAJO
a2fa0c39,2023-02-18 19:24:00,SEN4,17.0,42.5,1007.7,viento moderado,MODERADO
864d8ba3,2023-02-24 19:07:00,SEN5,29.8,66.9,1002.3,2025-09-08 00:00:00,BAJO
691a8c22,2023-02-27 19:07:00,SEN2,29.8,86.3,1011.4,2025-06-08 00:00:00,MODERADO
1c555871,2023-02-27 20:40:00,SEN1,29.8,86.7,1015.8,2025-04-13 00:00:00,BAJO
920aabaf,2023-03-05 20:04:00,SEN4,32.6,52.2,1020.7,2025-09-08 00:00:00,MODERADO

In [37]:
df.dtypes

fecha_hora          datetime64[ns]
id_sensor                   object
temperatura (°C)           float64
humedad                    float64
presión                    float64
vel_viento                  object
rayos_uv                    object
dtype: object

In [38]:
df['vel_viento'].value_counts()

vel_viento
viento moderado        13
2025-03-09 00:00:00     3
2025-08-07 00:00:00     3
2025-07-16 00:00:00     2
2025-08-17 00:00:00     2
                       ..
2025-09-13 00:00:00     1
2025-08-04 00:00:00     1
2025-05-08 00:00:00     1
2025-02-05 00:00:00     1
2025-02-01 00:00:00     1
Name: count, Length: 71, dtype: int64

La columna vel_viento del df contiene datos muy confusos. No se entiende que tipo de registro se busco realizar. En dicha columna, los datos almacenados son de tipo object (string) y se encuentran registradas fechas, el string 'viento moderado' y algunos pocos datos numericos. Ante la imposibilidad de saber con exactitud que tipo de registro se busco realizar (velocidad del viento en kilometros o un string describiendo la intensidad del viento), se procedera a eliminar la columna del dataframe.

In [39]:
#verificar la cantidad de veces que un string que inicia con la palabra 'viento' se repite en la columna vel_viento
df['vel_viento'].str.contains('viento').value_counts()

vel_viento
True     13
False     9
Name: count, dtype: int64

In [40]:
#misma solucion que la anterior. Se obtiene las filas de datos que contienen el string 'viento' en la columna vel_viento
velocidades_viento = df[df['vel_viento'].str.startswith('viento', na=False)]
velocidades_viento.shape[0]

13

In [41]:
#eliminar la columna vel_viento del dataframe
df.drop('vel_viento', axis=1, inplace=True)
df.head()

,fecha_hora,id_sensor,temperatura (°C),humedad,presión,rayos_uv
id_medición,,,,,,
1473229f,2023-01-01 14:11:00,SEN1,29.8,66.4,1017.5,MODERADO
8e576280,2023-01-03 06:38:00,SEN2,33.6,42.0,1004.4,BAJO
99c4533b,2023-01-03 09:58:00,SEN5,29.8,65.3,1007.8,MODERADO
1580151b,2023-01-03 17:05:00,SEN4,29.8,40.5,1013.1,MODERADO
fb444e43,2023-01-03 21:25:00,SEN4,29.8,86.8,997.8,NULO

**Obtener la cantidad de veces que cada sensor registro mediciones**

In [42]:
df['id_sensor'].value_counts()

id_sensor
SEN5    24
SEN2    21
SEN1    19
SEN3    19
SEN4    17
Name: count, dtype: int64

**Obtener la cantidad de veces que se registro cada nivel de rayos uv**

In [43]:
df['rayos_uv'].value_counts()

rayos_uv
NULO        38
MODERADO    24
BAJO        23
ALTO        15
Name: count, dtype: int64

**Obtener la cantidad de veces que el SEN5 registro cada valor de rayos uv**

In [44]:
df[df['id_sensor'] == 'SEN5']['rayos_uv'].value_counts()

rayos_uv
NULO        10
BAJO         6
ALTO         5
MODERADO     3
Name: count, dtype: int64

**Obtener la cantidad de veces que el nivel de rayos uv MODERADO fue registrado por cada sensor**

In [45]:
df[df['rayos_uv'] == 'MODERADO']['id_sensor'].value_counts()

id_sensor
SEN2    7
SEN4    6
SEN3    5
SEN1    3
SEN5    3
Name: count, dtype: int64

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100 entries, 1473229f to a1073a10
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   fecha_hora        100 non-null    datetime64[ns]
 1   id_sensor         100 non-null    object
 2   temperatura (°C)  100 non-null    float64
 3   humedad           100 non-null    float64
 4   presión           100 non-null    float64
 5   rayos_uv          100 non-null    object
dtypes: datetime64[ns](1), float64(3), object(2)
memory usage: 9.5+ KB

**Obtener estadisticas basicas de las columnas con datos numericos**

In [47]:
df['temperatura (°C)'].describe()

count    100.00000
mean      29.78700
std        3.09544
min       15.00000
25%       29.80000
50%       29.80000
75%       29.80000
max       34.30000
Name: temperatura (°C), dtype: float64

In [48]:
df['humedad'].describe()

count    100.000000
mean      63.705000
std       13.946915
min       40.500000
25%       52.900000
50%       63.700000
75%       73.425000
max       89.200000
Name: humedad, dtype: float64

In [49]:
df['presión'].describe()

count     100.000000
mean     1008.746000
std         9.683595
min       991.000000
25%      1001.200000
50%      1010.000000
75%      1016.950000
max      1024.400000
Name: presión, dtype: float64

In [50]:
#exportar el archivo csv
df.to_csv('mediciones_sensores_limpio.csv', index=False)

In [51]:
#exportar el archivo csv limpio a hoja de calculo
df.to_excel('mediciones_sensores_limpio.xlsx', index=False)