<a href="https://colab.research.google.com/github/mfernandezzz/mediciones_sensores/blob/main/mediciones_sensores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Realizar una limpieza de datos lo mas acertada posible de una hoja de calculo que contiene registros correspondientes a mediciones de sensores.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
#cargar la hoja de calculo
df = pd.read_excel('/content/mediciones_sensores.xlsx')
df

,id_medición,fecha_hora,id_sensor,temperatura,humedad,presión,vel_viento,rayos_uv
0,81a078fe,2023-02-28 04:50:00,sen3,32.5°C,NaN,1022.4,viento moderado,ALTO
1,43cfa7ba,2023-01-11 03:12:00,SEN5,34.3,68.9,1017.4,3.0,Alto
2,8e576280,2023-01-03 06:38:00,SEN2,33.6,42.0,1004.4,2025-08-13 00:00:00,ALTO
3,611a37c3,2023-03-09 11:56:00,SEN3,2025-01-30 00:00:00,44.1,1013.4,2025-09-17 00:00:00,Alto
4,50ff25ae,2023-01-26 00:48:00,SEN1,2025-08-28 00:00:00,72.9,1015.7,2025-02-17 00:00:00,Bajo
...,...,...,...,...,...,...,...,...
100,893930,2023-02-02 08:06:00,SEN1,2025-07-29 00:00:00,57.9,1011.7,2025-08-16 00:00:00,ALTO
101,f63d551d,2023-01-04 22:55:00,SEN3,2025-05-16 00:00:00,52.6,1013.2,2025-03-09 00:00:00,ALTO
102,49aa188d,2023-03-02 04:33:00,sen3,2025-08-22 00:00:00,74.6,997.4,2025-08-10 00:00:00,moderado
103,b27c833b,2023-01-10 07:16:00,SEN4,32.5°C,NaN,1014.0,2025-06-01 00:00:00,Bajo
104,895b9285,2023-01-31 15:18:00,SEN5,31.0,77.1,1018.2,2025-09-17 00:00:00,Moderado

In [3]:
#pasar la hoja de calculo a un archivo csv
df.to_csv('mediciones_sensores.csv') #index=False, encoding='utf-8'

In [4]:
df.head()

,id_medición,fecha_hora,id_sensor,temperatura,humedad,presión,vel_viento,rayos_uv
0,81a078fe,2023-02-28 04:50:00,sen3,32.5°C,NaN,1022.4,viento moderado,ALTO
1,43cfa7ba,2023-01-11 03:12:00,SEN5,34.3,68.9,1017.4,3.0,Alto
2,8e576280,2023-01-03 06:38:00,SEN2,33.6,42.0,1004.4,2025-08-13 00:00:00,ALTO
3,611a37c3,2023-03-09 11:56:00,SEN3,2025-01-30 00:00:00,44.1,1013.4,2025-09-17 00:00:00,Alto
4,50ff25ae,2023-01-26 00:48:00,SEN1,2025-08-28 00:00:00,72.9,1015.7,2025-02-17 00:00:00,Bajo

In [5]:
#visualizar el tipo de dato que almacena cada columna
df.dtypes

id_medición            object
fecha_hora     datetime64[ns]
id_sensor              object
temperatura            object
humedad               float64
presión               float64
vel_viento             object
rayos_uv               object
dtype: object

In [6]:
#comprobar si un id se repite mas de una vez (filas duplicadas)
df['id_medición'].value_counts()

id_medición
49aa188d    2
f63d551d    2
895b9285    2
b27c833b    2
893930      2
           ..
3bb53859    1
fed7c593    1
bbd0c5b3    1
f0f22f0a    1
1f1d6bd1    1
Name: count, Length: 100, dtype: int64

In [7]:
#establecer la columna id_medicion como el indice del dataframe
df.set_index('id_medición', inplace=True)
df

,fecha_hora,id_sensor,temperatura,humedad,presión,vel_viento,rayos_uv
id_medición,,,,,,,
81a078fe,2023-02-28 04:50:00,sen3,32.5°C,NaN,1022.4,viento moderado,ALTO
43cfa7ba,2023-01-11 03:12:00,SEN5,34.3,68.9,1017.4,3.0,Alto
8e576280,2023-01-03 06:38:00,SEN2,33.6,42.0,1004.4,2025-08-13 00:00:00,ALTO
611a37c3,2023-03-09 11:56:00,SEN3,2025-01-30 00:00:00,44.1,1013.4,2025-09-17 00:00:00,Alto
50ff25ae,2023-01-26 00:48:00,SEN1,2025-08-28 00:00:00,72.9,1015.7,2025-02-17 00:00:00,Bajo
...,...,...,...,...,...,...,...
893930,2023-02-02 08:06:00,SEN1,2025-07-29 00:00:00,57.9,1011.7,2025-08-16 00:00:00,ALTO
f63d551d,2023-01-04 22:55:00,SEN3,2025-05-16 00:00:00,52.6,1013.2,2025-03-09 00:00:00,ALTO
49aa188d,2023-03-02 04:33:00,sen3,2025-08-22 00:00:00,74.6,997.4,2025-08-10 00:00:00,moderado
b27c833b,2023-01-10 07:16:00,SEN4,32.5°C,NaN,1014.0,2025-06-01 00:00:00,Bajo
895b9285,2023-01-31 15:18:00,SEN5,31.0,77.1,1018.2,2025-09-17 00:00:00,Moderado

In [8]:
#comprobar la cantidad de sensores
df['id_sensor'].value_counts()

id_sensor
SEN5    23
SEN2    19
SEN1    18
SEN4    18
SEN3    16
sen3     5
sen1     2
sen2     2
sen5     2
Name: count, dtype: int64

In [9]:
#pasar los id de sensores en minuscula a mayuscula
df['id_sensor'] = df['id_sensor'].str.upper()
df['id_sensor'].value_counts()

id_sensor
SEN5    25
SEN3    21
SEN2    21
SEN1    20
SEN4    18
Name: count, dtype: int64

In [10]:
#buscar errores de tipeo en la columna rayos_uv
df['rayos_uv'].value_counts()

rayos_uv
ALTO        23
Alto        23
Bajo        21
moderado    20
Moderado    18
Name: count, dtype: int64

In [11]:
#corregir los errores de tipeo en la columna rayos_uv
df['rayos_uv'] = df['rayos_uv'].str.upper()
df['rayos_uv'].value_counts()

rayos_uv
ALTO        46
MODERADO    38
BAJO        21
Name: count, dtype: int64

In [12]:
#visualizar la cantidad de filas que tiene el dataframe
df.shape[0]

105

In [13]:
#eliminar filas duplicadas y ordenar las filas en base a la columna fecha y hora
df = df.drop_duplicates().sort_values('fecha_hora')
df.shape[0]

100

In [14]:
#observar los registros en la columna vel_viento
df['vel_viento'].value_counts()

vel_viento
viento moderado        13
2025-03-09 00:00:00     3
2025-08-07 00:00:00     3
2025-07-16 00:00:00     2
2025-08-17 00:00:00     2
                       ..
2025-09-13 00:00:00     1
2025-08-04 00:00:00     1
2025-05-08 00:00:00     1
2025-02-05 00:00:00     1
2025-02-01 00:00:00     1
Name: count, Length: 71, dtype: int64

In [15]:
#comprobar si solo se encuentra el string viento moderado en la columna vel_viento
velocidades_viento = df[df['vel_viento'].str.startswith('viento', na=False)]
velocidades_viento.shape[0]

13

In [16]:
#cambiar todos los datos de la columna vel_viento a viento moderado (no parece importante btw)
df['vel_viento'] = 'viento moderado'
df['vel_viento'].value_counts()

vel_viento
viento moderado    100
Name: count, dtype: int64

In [17]:
df.head(10)

,fecha_hora,id_sensor,temperatura,humedad,presión,vel_viento,rayos_uv
id_medición,,,,,,,
1473229f,2023-01-01 14:11:00,SEN1,2025-02-28 00:00:00,66.4,1017.5,viento moderado,MODERADO
8e576280,2023-01-03 06:38:00,SEN2,33.6,42.0,1004.4,viento moderado,ALTO
99c4533b,2023-01-03 09:58:00,SEN5,2025-03-25 00:00:00,65.3,1007.8,viento moderado,MODERADO
1580151b,2023-01-03 17:05:00,SEN4,2025-01-15 00:00:00,40.5,1013.1,viento moderado,MODERADO
fb444e43,2023-01-03 21:25:00,SEN4,2025-08-26 00:00:00,86.8,997.8,viento moderado,BAJO
f63d551d,2023-01-04 22:55:00,SEN3,2025-05-16 00:00:00,52.6,1013.2,viento moderado,ALTO
f8f58403,2023-01-05 04:06:00,SEN2,15.0,87.3,1000.6,viento moderado,ALTO
e6bf6b53,2023-01-07 07:56:00,SEN2,2025-03-18 00:00:00,45.6,1019.2,viento moderado,MODERADO
c1ed9550,2023-01-07 11:58:00,SEN5,32.5°C,NaN,991.6,viento moderado,ALTO
8d573a04,2023-01-08 04:08:00,SEN1,2025-03-15 00:00:00,42.2,1014.4,viento moderado,ALTO

In [18]:
#cambiar el nombre de la columna temperatura
cols = df.columns.tolist()
cols[cols.index('temperatura')] = 'temperatura (°C)'
df.columns = cols
df.head(10)

,fecha_hora,id_sensor,temperatura (°C),humedad,presión,vel_viento,rayos_uv
id_medición,,,,,,,
1473229f,2023-01-01 14:11:00,SEN1,2025-02-28 00:00:00,66.4,1017.5,viento moderado,MODERADO
8e576280,2023-01-03 06:38:00,SEN2,33.6,42.0,1004.4,viento moderado,ALTO
99c4533b,2023-01-03 09:58:00,SEN5,2025-03-25 00:00:00,65.3,1007.8,viento moderado,MODERADO
1580151b,2023-01-03 17:05:00,SEN4,2025-01-15 00:00:00,40.5,1013.1,viento moderado,MODERADO
fb444e43,2023-01-03 21:25:00,SEN4,2025-08-26 00:00:00,86.8,997.8,viento moderado,BAJO
f63d551d,2023-01-04 22:55:00,SEN3,2025-05-16 00:00:00,52.6,1013.2,viento moderado,ALTO
f8f58403,2023-01-05 04:06:00,SEN2,15.0,87.3,1000.6,viento moderado,ALTO
e6bf6b53,2023-01-07 07:56:00,SEN2,2025-03-18 00:00:00,45.6,1019.2,viento moderado,MODERADO
c1ed9550,2023-01-07 11:58:00,SEN5,32.5°C,NaN,991.6,viento moderado,ALTO
8d573a04,2023-01-08 04:08:00,SEN1,2025-03-15 00:00:00,42.2,1014.4,viento moderado,ALTO

In [19]:
#verificar si la columna presion contiene valores nulos (nan)
presion_null = np.isnan(df['presión'])
presion_null.value_counts()

presión
False    100
Name: count, dtype: int64

In [20]:
#verificar si la columna humedad contiene valores nulos
humedad_null = np.isnan(df['humedad'])
humedad_null.value_counts()

humedad
False    88
True     12
Name: count, dtype: int64

In [21]:
#obtener un numpy array con todos los valores dentro de la columna humedad
humedad_values = np.array(df['humedad'])
#obtener el valor medio de humedad excluyendo los valores nan
mean_humedad = humedad_values[~np.isnan(humedad_values)].mean()
round(mean_humedad, 1)

np.float64(63.7)

In [22]:
#obtener el valor minimo de humedad
min_humedad = humedad_values[~np.isnan(humedad_values)].min()
min_humedad

np.float64(40.5)

In [23]:
#obtener el valor maximo de humedad
max_humedad = humedad_values[~np.isnan(humedad_values)].max()
max_humedad

np.float64(89.2)

In [24]:
#obtener la desviacion estandar de los valores de humedad
std_humedad = humedad_values[~np.isnan(humedad_values)].std()
round(std_humedad, 1)

np.float64(14.8)

In [25]:
#sustituir los valores nan por el valor medio de humedad obtenido previamente
df['humedad'] = df['humedad'].fillna(round(mean_humedad, 1))
df.head(10)

,fecha_hora,id_sensor,temperatura (°C),humedad,presión,vel_viento,rayos_uv
id_medición,,,,,,,
1473229f,2023-01-01 14:11:00,SEN1,2025-02-28 00:00:00,66.4,1017.5,viento moderado,MODERADO
8e576280,2023-01-03 06:38:00,SEN2,33.6,42.0,1004.4,viento moderado,ALTO
99c4533b,2023-01-03 09:58:00,SEN5,2025-03-25 00:00:00,65.3,1007.8,viento moderado,MODERADO
1580151b,2023-01-03 17:05:00,SEN4,2025-01-15 00:00:00,40.5,1013.1,viento moderado,MODERADO
fb444e43,2023-01-03 21:25:00,SEN4,2025-08-26 00:00:00,86.8,997.8,viento moderado,BAJO
f63d551d,2023-01-04 22:55:00,SEN3,2025-05-16 00:00:00,52.6,1013.2,viento moderado,ALTO
f8f58403,2023-01-05 04:06:00,SEN2,15.0,87.3,1000.6,viento moderado,ALTO
e6bf6b53,2023-01-07 07:56:00,SEN2,2025-03-18 00:00:00,45.6,1019.2,viento moderado,MODERADO
c1ed9550,2023-01-07 11:58:00,SEN5,32.5°C,63.7,991.6,viento moderado,ALTO
8d573a04,2023-01-08 04:08:00,SEN1,2025-03-15 00:00:00,42.2,1014.4,viento moderado,ALTO

In [26]:
#verificar si la columna humedad sigue teniendo valores nan
humedad_null = np.isnan(df['humedad'])
humedad_null.value_counts()

humedad
False    100
Name: count, dtype: int64

In [27]:
#obtener el valor medio de humedad con los datos limpiados
round(df['humedad'].mean(), 1)

np.float64(63.7)

In [28]:
#obtener la desviacion estandar de los valores de humedad con los datos limpiados
round(df['humedad'].std(), 1)

13.9

In [29]:
#eliminar todos los datos que incluyan ºC en la columna temperatura
df['temperatura (°C)'] = df['temperatura (°C)'].str.replace('°C', '')
df.head(10)

,fecha_hora,id_sensor,temperatura (°C),humedad,presión,vel_viento,rayos_uv
id_medición,,,,,,,
1473229f,2023-01-01 14:11:00,SEN1,NaN,66.4,1017.5,viento moderado,MODERADO
8e576280,2023-01-03 06:38:00,SEN2,33.6,42.0,1004.4,viento moderado,ALTO
99c4533b,2023-01-03 09:58:00,SEN5,NaN,65.3,1007.8,viento moderado,MODERADO
1580151b,2023-01-03 17:05:00,SEN4,NaN,40.5,1013.1,viento moderado,MODERADO
fb444e43,2023-01-03 21:25:00,SEN4,NaN,86.8,997.8,viento moderado,BAJO
f63d551d,2023-01-04 22:55:00,SEN3,NaN,52.6,1013.2,viento moderado,ALTO
f8f58403,2023-01-05 04:06:00,SEN2,15.0,87.3,1000.6,viento moderado,ALTO
e6bf6b53,2023-01-07 07:56:00,SEN2,NaN,45.6,1019.2,viento moderado,MODERADO
c1ed9550,2023-01-07 11:58:00,SEN5,32.5,63.7,991.6,viento moderado,ALTO
8d573a04,2023-01-08 04:08:00,SEN1,NaN,42.2,1014.4,viento moderado,ALTO

In [30]:
#visualizar la cantidad de valores de temperatura registrados en la columna
df['temperatura (°C)'].value_counts()

temperatura (°C)
32.5    8
33.0    2
32.3    2
15.0    1
29.2    1
33.6    1
34.3    1
28.0    1
32.0    1
23.0    1
33.5    1
32.2    1
16.0    1
31.0    1
32.1    1
33.8    1
17.0    1
24.0    1
33.4    1
32.6    1
31.2    1
20.0    1
Name: count, dtype: int64

In [31]:
#cambiar los valores de la columna temperatura a type float
df['temperatura (°C)'] = df['temperatura (°C)'].astype(float)
df.dtypes

fecha_hora          datetime64[ns]
id_sensor                   object
temperatura (°C)           float64
humedad                    float64
presión                    float64
vel_viento                  object
rayos_uv                    object
dtype: object

In [32]:
#obtener los valores de temperatura
values_temperatura = np.array(df['temperatura (°C)'])
values_temperatura

array([ nan, 33.6,  nan,  nan,  nan,  nan, 15. ,  nan, 32.5,  nan,  nan,
        nan,  nan, 29.2,  nan, 32.5, 32.5, 33. , 34.3, 28. ,  nan,  nan,
        nan,  nan,  nan, 32. , 32.3,  nan,  nan,  nan,  nan,  nan, 23. ,
       33.5,  nan,  nan, 32.2,  nan, 32.5, 16. ,  nan,  nan,  nan,  nan,
        nan,  nan, 31. ,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan, 32.5, 32.5,  nan,  nan,  nan, 32.1, 33.8,  nan,
        nan, 17. ,  nan,  nan, 32.5,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan, 32.5,  nan,  nan,  nan,  nan, 24. ,
       33.4, 32.3, 32.6,  nan, 33. ,  nan,  nan, 31.2,  nan, 20. ,  nan,
        nan])

In [33]:
#obtener el valor medio de temperatura excluyendo los valores nan
mean_temperatura = values_temperatura[~np.isnan(values_temperatura)].mean()
round(mean_temperatura, 1)

np.float64(29.8)

In [34]:
#obtener el valor minimo de temperatura excluyendo los valores nan
min_temperatura = values_temperatura[~np.isnan(values_temperatura)].min()
min_temperatura

np.float64(15.0)

In [35]:
#obtener el valor maximo de temperatura excluyendo los valores nan
max_temperatura = values_temperatura[~np.isnan(values_temperatura)].max()
max_temperatura

np.float64(34.3)

In [36]:
#obtener la desviacion estandar de los valores de temperatura excluyendo los valores nan
std_temperatura = values_temperatura[~np.isnan(values_temperatura)].std()
round(std_temperatura, 1)

np.float64(5.5)

In [37]:
#sustituir los valores nan por los valores medios de temperatura
df['temperatura (°C)'] = df['temperatura (°C)'].fillna(round(mean_temperatura, 1))
df.head(10)

,fecha_hora,id_sensor,temperatura (°C),humedad,presión,vel_viento,rayos_uv
id_medición,,,,,,,
1473229f,2023-01-01 14:11:00,SEN1,29.8,66.4,1017.5,viento moderado,MODERADO
8e576280,2023-01-03 06:38:00,SEN2,33.6,42.0,1004.4,viento moderado,ALTO
99c4533b,2023-01-03 09:58:00,SEN5,29.8,65.3,1007.8,viento moderado,MODERADO
1580151b,2023-01-03 17:05:00,SEN4,29.8,40.5,1013.1,viento moderado,MODERADO
fb444e43,2023-01-03 21:25:00,SEN4,29.8,86.8,997.8,viento moderado,BAJO
f63d551d,2023-01-04 22:55:00,SEN3,29.8,52.6,1013.2,viento moderado,ALTO
f8f58403,2023-01-05 04:06:00,SEN2,15.0,87.3,1000.6,viento moderado,ALTO
e6bf6b53,2023-01-07 07:56:00,SEN2,29.8,45.6,1019.2,viento moderado,MODERADO
c1ed9550,2023-01-07 11:58:00,SEN5,32.5,63.7,991.6,viento moderado,ALTO
8d573a04,2023-01-08 04:08:00,SEN1,29.8,42.2,1014.4,viento moderado,ALTO

In [38]:
#obtener el valor medio de temperatura con los datos limpiados
round(df['temperatura (°C)'].mean(), 1)

np.float64(29.8)

In [39]:
#obtener el desvio estandar de temperatura con los datos limpiados
round(df['temperatura (°C)'].std(), 1)

3.1

In [40]:
#obtener el valor minimo de presion atmosferica
df['presión'].min()

991.0

In [41]:
#obtener el valor maximo de presion atmosferica
df['presión'].max()

1024.4

In [42]:
#obtener el valor medio de presion atmosferica
round(df['presión'].mean(), 1)

np.float64(1008.7)

In [43]:
#obtener la desviacion estandar de presion atmosferica
round(df['presión'].std(), 1)

9.7

In [44]:
#obtener la cantidad de veces que cada sensor registro una medicion
df['id_sensor'].value_counts()

id_sensor
SEN5    24
SEN2    21
SEN1    19
SEN3    19
SEN4    17
Name: count, dtype: int64

In [45]:
#obtener la cantidad de veces que se repiten los niveles de rayos uv
df['rayos_uv'].value_counts()

rayos_uv
ALTO        44
MODERADO    36
BAJO        20
Name: count, dtype: int64

In [46]:
#obtener la cantidad de veces que el sensor con id SEN5 registro los respectivos valores de rayos uv
df[df['id_sensor'] == 'SEN5']['rayos_uv'].value_counts()

rayos_uv
ALTO        13
MODERADO     7
BAJO         4
Name: count, dtype: int64

In [47]:
#obtener la cantidad de veces que el valor de rayos uv ALTO fue registrado por los demas sensores
df[df['rayos_uv'] == 'ALTO']['id_sensor'].value_counts()

id_sensor
SEN5    13
SEN2     9
SEN3     9
SEN1     8
SEN4     5
Name: count, dtype: int64

In [48]:
df.head(15)

,fecha_hora,id_sensor,temperatura (°C),humedad,presión,vel_viento,rayos_uv
id_medición,,,,,,,
1473229f,2023-01-01 14:11:00,SEN1,29.8,66.4,1017.5,viento moderado,MODERADO
8e576280,2023-01-03 06:38:00,SEN2,33.6,42.0,1004.4,viento moderado,ALTO
99c4533b,2023-01-03 09:58:00,SEN5,29.8,65.3,1007.8,viento moderado,MODERADO
1580151b,2023-01-03 17:05:00,SEN4,29.8,40.5,1013.1,viento moderado,MODERADO
fb444e43,2023-01-03 21:25:00,SEN4,29.8,86.8,997.8,viento moderado,BAJO
f63d551d,2023-01-04 22:55:00,SEN3,29.8,52.6,1013.2,viento moderado,ALTO
f8f58403,2023-01-05 04:06:00,SEN2,15.0,87.3,1000.6,viento moderado,ALTO
e6bf6b53,2023-01-07 07:56:00,SEN2,29.8,45.6,1019.2,viento moderado,MODERADO
c1ed9550,2023-01-07 11:58:00,SEN5,32.5,63.7,991.6,viento moderado,ALTO
8d573a04,2023-01-08 04:08:00,SEN1,29.8,42.2,1014.4,viento moderado,ALTO
412652be,2023-01-08 06:18:00,SEN5,29.8,41.8,1001.3,viento moderado,ALTO
9af46357,2023-01-08 21:55:00,SEN3,29.8,72.3,1002.2,viento moderado,BAJO
d3057fef,2023-01-09 10:36:00,SEN5,29.8,47.8,1022.9,viento moderado,ALTO
6d71f038,2023-01-09 12:40:00,SEN2,29.2,63.7,1003.9,viento moderado,MODERADO
363aee17,2023-01-09 19:16:00,SEN5,29.8,50.5,996.9,viento moderado,BAJO

In [49]:
#exportar el archivo csv limpio a hoja de calculo
df.to_excel('mediciones_sensores_limpio.xlsx', index=False)